### PR TITLE
add pre compile hook

### PR DESCRIPTION
**Pull request by aliak00**
Allows you to do execute stuff before the compile step is run, maybe
to decrypt files, wget things from the network, or setup your env
even further

### CODE REVIEW

**Comment by aliak00** [comment]
BTW: I also added [a pre install environment hook](https://github.com/aliak00/heroku-buildpack-d/commit/c1899cb9036babaeae2714840cd8d881faccf1c9) since the dlang.org/install.sh uses some vars and I needed to customize some of those

PS: Do you know why the dlang.org/install.sh script [tries to use gpg2 first](https://github.com/dlang/installer/blob/955065652a752a1b43f0da5addb3ed283ad2f0ab/script/install.sh#L564) when verifying the signature? This makes the build pack fail if I install gpg2 since that doesn't verify the d gpg keyring file properly I guess.

and because of the sourcing hook I also got rid of d-compiler since [you can source it](https://github.com/aliak00/heroku-buildpack-d/commit/0f1ee7da9ceca50bdfdf96732cedf508321446eb) now

**Comment by MartinNowak** [comment]
Thanks for your PR :), sorry for the late response :/.

> Allows you to do execute stuff before the compile step is run

Why not use dub's pre-build step instead?

> BTW: I also added [a pre install environment hook](https://github.com/aliak00/heroku-buildpack-d/commit/c1899cb9036babaeae2714840cd8d881faccf1c9) since the dlang.org/install.sh uses some vars and I needed to customize some of those

What kind of env customization did you have in mind? It's asking for trouble to mess with the build environment (PATH, LIBRARY_PATH, LD_LIBRARY_PATH).
If it's meant to add custom linker paths or libs that are present in your package, dub should be able to handle that (see libs and lflags in https://code.dlang.org/package-format?lang=sdl).

**Comment by aliak00** [comment]
Oh my this is still here :p Yeah, good point about dub's prebuild step, I think I didn't know that existed when I put this up. Sounds like that should work. 

The env was related to the gpg stuff the install script does (this was quite a while ago so I don't remember the exact details, but) - I needed to `export GPG=gpg` before the install script was run because I had a dependency on gpg2. And the d install script was failing to verify its signatures with gpg2.

**Comment by MartinNowak** [comment]
>  And the d install script was failing to verify its signatures with gpg2.

That sounds bad @aliak00, any more details to reproduce the problem, like OS version and/or version of gpg2?

**Comment by MartinNowak** [comment]
See https://github.com/MartinNowak/heroku-buildpack-d/pull/6 for the PR.

**Comment by aliak00** [comment]
Nice! One thing that came to mind just now, is i guess you can have env vars in your heroku that could potentially clash with the build pack?

**Pull request closed without merging**
